---
# handlers file for setup-apache
- name: This handler will start httpd service on Redhat VMs
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"

- name: This handler will start apache2 service on Ubunt VMs
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"