---
- name:
  hosts: webservers
  become: yes

  tasks:
  - name: This task will copy index.html file to Webservers
    copy:
      src: /etc/ansible/index.html
      dest: /var/www/html
      mode: 0666