---
- name: This playbook will create directory and file inside directory in all hosts
  hosts: all
  become: true

  tasks:
  - name: This task will a create directory if it does not exist
    file:
      path: /home/ansadmin/test_directory
      state: directory
      mode: 0744
  
  - name: This task will create a file
    file:
      path: /home/ansadmin/test_directory/test_file
      state: touch
      mode: 0744

  - name: This task will change the owner of test_directory recursivly
    file:
      path: /home/ansadmin/test_directory
      recurse: yes
      owner: ansadmin
      group: ansadmin