---
- name: This playbook will remove directory recusivly
  hosts: all
  become: true
  become_user: ansadmin
  

  tasks:
  - name: This task will remove directory
    file:
      path: /home/ansadmin/test_directory
      state: absent