---
# tasks file for setup-apache
- name: Install httpd on Redhat
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: This task will change SELINUX config to allow to change httpd port to {{ custom_port }}
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
  when: ansible_os_family == "RedHat"

- name: Unconditionally reboot the machine with all defaults
  reboot:

- name: This task will start httpd service on boot on  Redhat VMs
  systemd:
    name: httpd
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install apache2 to Ubuntu
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: This task will start apache2 service on Ubunt VMs
  systemd:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"

- name: This task will start httpd service on boot on Debian VMs
  systemd:
    name: apache2
    enabled: yes
  when: ansible_os_family == "Debian"

- name: This task will copy inxdex.html file to managed-nodes
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: 0666

- name: This task will change httpd port number to {{ custom_port }} on RedHat Family VMs
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen {{ custom_port }}
  when: ansible_os_family == "RedHat"

- name: This task will restart httpd service on Redhat VMs
  systemd:
    name: httpd
    state: reloaded
  when: ansible_os_family == "RedHat"

- name: This task will change apache2 port number to {{ custom_port }} on Debian Family VMs
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen '
    insertafter: '#/etc/apache2/sites-enabled/000-default.conf'
    line: Listen {{ custom_port }}
  when: ansible_os_family == "Debian"

- name: This task will restart apache2 service on Ubunt VMs
  systemd:
    name: apache2
    state: reloaded
  when: ansible_os_family == "Debian"